#include <stdio.h>
#include <stdint.h>

#include "marsh_poke.h"


static const char* marsh_poke_names[] = {
	"Croagunk",  "Skorupi",  "Carnivine",  "Golduck",
	"Roselia",   "Staravia", "Marill",     "Azurill",
	"Wooper",    "Quagsire", "Bidoof",     "Bibarel",
	"Toxicroak", "Drapion",  "Exeggcute",  "Yanma",
	"Shroomish", "Paras",    "Kangaskhan", "Gulpin",
	"Tropius",   "Tangela",  "Kecleon",    NULL
};

static const char* get_marsh_poke_name(marsh_poke poke) {
	int i = -1;
	while (poke != 0) {
		poke >>= 1;
		i++;
	}
	
	return marsh_poke_names[i];
}


static const marsh_poke marsh_poke_tables[4][32] = {
	/* DP_NO_NAT_DEX */
	{
		MARSH_POKE_CROAGUNK,  MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE, MARSH_POKE_CROAGUNK, 
		MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE, MARSH_POKE_GOLDUCK,   MARSH_POKE_CROAGUNK, 
		MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE, MARSH_POKE_ROSELIA,   MARSH_POKE_STARAVIA, 
		MARSH_POKE_MARILL,    MARSH_POKE_AZURILL,   MARSH_POKE_WOOPER,    MARSH_POKE_GOLDUCK, 
		MARSH_POKE_STARAVIA,  MARSH_POKE_CROAGUNK,  MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE, 
		MARSH_POKE_QUAGSIRE,  MARSH_POKE_BIDOOF,    MARSH_POKE_BIBAREL,   MARSH_POKE_WOOPER,
		MARSH_POKE_AZURILL,   MARSH_POKE_ROSELIA,   MARSH_POKE_STARAVIA,  MARSH_POKE_CROAGUNK, 
		MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE, MARSH_POKE_ROSELIA,   MARSH_POKE_GOLDUCK
	},
	
	/* DP_NAT_DEX */
	{
		MARSH_POKE_CROAGUNK,  MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE, MARSH_POKE_CROAGUNK,
		MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE, MARSH_POKE_GOLDUCK,   MARSH_POKE_CROAGUNK,
		MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE, MARSH_POKE_ROSELIA,   MARSH_POKE_STARAVIA,
		MARSH_POKE_TOXICROAK, MARSH_POKE_DRAPION,   MARSH_POKE_EXEGGCUTE, MARSH_POKE_GOLDUCK,
		MARSH_POKE_STARAVIA,  MARSH_POKE_CROAGUNK,  MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE,
		MARSH_POKE_YANMA,     MARSH_POKE_SHROOMISH, MARSH_POKE_PARAS,     MARSH_POKE_KANGASKHAN,
		MARSH_POKE_GULPIN,    MARSH_POKE_ROSELIA,   MARSH_POKE_STARAVIA,  MARSH_POKE_CROAGUNK,
		MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE, MARSH_POKE_ROSELIA,   MARSH_POKE_GOLDUCK
	},
	
	/* PT_NO_NAT_DEX */
	{
		MARSH_POKE_WOOPER,    MARSH_POKE_WOOPER,    MARSH_POKE_WOOPER,    MARSH_POKE_CARNIVINE,
		MARSH_POKE_SKORUPI,   MARSH_POKE_CROAGUNK,  MARSH_POKE_QUAGSIRE,  MARSH_POKE_WOOPER,
		MARSH_POKE_SKORUPI,   MARSH_POKE_CROAGUNK,  MARSH_POKE_QUAGSIRE,  MARSH_POKE_WOOPER,
		MARSH_POKE_WOOPER,    MARSH_POKE_WOOPER,    MARSH_POKE_WOOPER,    MARSH_POKE_WOOPER,
		MARSH_POKE_SKORUPI,   MARSH_POKE_CROAGUNK,  MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE,
		MARSH_POKE_YANMA,     MARSH_POKE_WOOPER,    MARSH_POKE_WOOPER,    MARSH_POKE_WOOPER,
		MARSH_POKE_WOOPER,    MARSH_POKE_TROPIUS,   MARSH_POKE_WOOPER,    MARSH_POKE_WOOPER,
		MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE, MARSH_POKE_CROAGUNK,  MARSH_POKE_TANGELA
	},
	
	/* PT_NAT_DEX */
	{
		MARSH_POKE_TOXICROAK, MARSH_POKE_KECLEON,   MARSH_POKE_KECLEON,   MARSH_POKE_CARNIVINE,
		MARSH_POKE_SKORUPI,   MARSH_POKE_CROAGUNK,  MARSH_POKE_QUAGSIRE,  MARSH_POKE_DRAPION,
		MARSH_POKE_SKORUPI,   MARSH_POKE_CROAGUNK,  MARSH_POKE_QUAGSIRE,  MARSH_POKE_KANGASKHAN,
		MARSH_POKE_PARAS,     MARSH_POKE_DRAPION,   MARSH_POKE_EXEGGCUTE, MARSH_POKE_EXEGGCUTE,
		MARSH_POKE_SKORUPI,   MARSH_POKE_CROAGUNK,  MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE,
		MARSH_POKE_YANMA,     MARSH_POKE_SHROOMISH, MARSH_POKE_PARAS,     MARSH_POKE_KANGASKHAN,
		MARSH_POKE_GULPIN,    MARSH_POKE_TROPIUS,   MARSH_POKE_GULPIN,    MARSH_POKE_SHROOMISH,
		MARSH_POKE_SKORUPI,   MARSH_POKE_CARNIVINE, MARSH_POKE_CROAGUNK,  MARSH_POKE_TANGELA
	}
};


static const marsh_poke marsh_poke_available[4][16] = {
	/* DP_NO_NAT_DEX */
	{
		MARSH_POKE_CROAGUNK, MARSH_POKE_SKORUPI,  MARSH_POKE_CARNIVINE, MARSH_POKE_GOLDUCK,
		MARSH_POKE_ROSELIA,  MARSH_POKE_STARAVIA, MARSH_POKE_MARILL,    MARSH_POKE_AZURILL,
		MARSH_POKE_WOOPER,   MARSH_POKE_QUAGSIRE, MARSH_POKE_BIDOOF,    MARSH_POKE_BIBAREL,
		MARSH_POKE_END
	},
	
	/* DP_NAT_DEX */
	{
		MARSH_POKE_CROAGUNK,   MARSH_POKE_SKORUPI,  MARSH_POKE_CARNIVINE, MARSH_POKE_GOLDUCK,
		MARSH_POKE_ROSELIA,    MARSH_POKE_STARAVIA, MARSH_POKE_TOXICROAK, MARSH_POKE_DRAPION,
		MARSH_POKE_EXEGGCUTE,  MARSH_POKE_YANMA,    MARSH_POKE_SHROOMISH, MARSH_POKE_PARAS,
		MARSH_POKE_KANGASKHAN, MARSH_POKE_GULPIN,
		MARSH_POKE_END
	},
	
	/* PT_NO_NAT_DEX */
	{
		MARSH_POKE_WOOPER,   MARSH_POKE_CARNIVINE, MARSH_POKE_SKORUPI, MARSH_POKE_CROAGUNK,
		MARSH_POKE_QUAGSIRE, MARSH_POKE_YANMA,     MARSH_POKE_TROPIUS, MARSH_POKE_TANGELA,
		MARSH_POKE_END
	},
	
	/* PT_NAT_DEX */
	{
		MARSH_POKE_TOXICROAK, MARSH_POKE_KECLEON,   MARSH_POKE_CARNIVINE, MARSH_POKE_SKORUPI,
		MARSH_POKE_CROAGUNK,  MARSH_POKE_QUAGSIRE,  MARSH_POKE_DRAPION,   MARSH_POKE_KANGASKHAN,
		MARSH_POKE_PARAS,     MARSH_POKE_EXEGGCUTE, MARSH_POKE_YANMA,     MARSH_POKE_SHROOMISH,
		MARSH_POKE_GULPIN,    MARSH_POKE_TROPIUS,   MARSH_POKE_TANGELA,
		MARSH_POKE_END
	}
};

unsigned int print_marsh_poke_options(game_details game) {
	unsigned int num = 1;
	const marsh_poke* options = marsh_poke_available[game];
	
	while (*options != MARSH_POKE_END) {
		const char* name = get_marsh_poke_name(*options);
		printf("%i) %s\n", num, name);
		
		num++;
		options++;
	}
	
	// Return: number of options it printed
	return num - 1;
}

marsh_poke get_marsh_poke_by_number(unsigned int num, game_details game) {
	return marsh_poke_available[game][num - 1];
}


marsh_poke_map groupseed_to_marsh_poke_map(uint32_t groupseed, game_details game) {
	const marsh_poke* game_table = marsh_poke_tables[game];
	
	marsh_poke_map result = 0;
	for (int i = 0; i < 6; i++) {
		result |= game_table[groupseed & 31];
		groupseed >>= 5;
	}
	
	return result;
}

void print_groupseed_marsh_pokes(uint32_t groupseed, game_details game) {
	const marsh_poke* game_table = marsh_poke_tables[game];
	
	for (int i = 0; i < 6; i++) {
		uint32_t poke = game_table[groupseed & 31];
		const char* name = get_marsh_poke_name(poke);
		printf("Area %i Poke: %s\n", i+1, name);
		groupseed >>= 5;
	}
}
